export const FETCH_RESUME_SKILLS = 'FETCH_RESUME_SKILLS';
export const FETCH_RESUME_EXPERIENCE = 'FETCH_RESUME_EXPERIENCE';
export const FETCH_RESUME_EDUCATION = 'FETCH_RESUME_EDUCATION';

export const FETCH_APP_SECTIONS = 'FETCH_APP_SECTIONS';
export const FETCH_APP_SECTION = 'FETCH_APP_SECTION';

export const FETCH_MENU_STATUS = 'FETCH_MENU_STATUS';
export const SET_MENU_STATUS = 'SET_MENU_STATUS';

export const FETCH_PROJECTS = 'FETCH_PROJECTS';
